
create table if not exists movimientos (
 id bigint generated by default as identity primary key,
 fecha date not null, tipo text not null, descripcion text default '',
 monto numeric(14,2) not null default 0, categoria text default 'Otros Gastos',
 comparte_tomas boolean not null default false, medio_pago text default '',
 cuotas integer not null default 1, mes_imputacion text, moneda text not null default 'ARS',
 cotizacion_mep numeric(14,4) not null default 0, monto_pesos numeric(14,2) not null default 0,
 created_at timestamptz not null default now()
);
create table if not exists tarjetas (
 id bigint generated by default as identity primary key, nombre text unique not null,
 limite numeric(14,2) not null default 0, activo boolean not null default true,
 created_at timestamptz not null default now()
);
create table if not exists categorias (
 id bigint generated by default as identity primary key, nombre text unique not null,
 activo boolean not null default true, created_at timestamptz not null default now()
);
create table if not exists gastos_fijos (
 id bigint generated by default as identity primary key, nombre text unique not null,
 monto numeric(14,2) not null default 0, dia_vencimiento integer not null default 10,
 activo boolean not null default true, confirmado_mes boolean not null default false,
 created_at timestamptz not null default now()
);
create table if not exists medios_pago (
 id bigint generated by default as identity primary key, nombre text unique not null,
 activo boolean not null default true, created_at timestamptz not null default now()
);

insert into categorias(nombre) values ('Compras Online / Impulsivas'),('Impuestos y Costos TC'),('Educación / Cursos'),('Delivery'),('Prepaga'),('Transporte / Auto'),('Salidas / Gastronomía'),('Otros Gastos'),('Luz'),('Seguros Adicionales'),('Telefonía'),('Agua'),('Gas'),('Profesional (Colegiatura)'),('Suscripciones'),('Supermercado'),('Tarjeta'),('Monotributo'),('Internet')
on conflict (nombre) do nothing;
insert into medios_pago(nombre) values ('Efectivo/MP'),('Tarjeta de Crédito')
on conflict (nombre) do nothing;
insert into gastos_fijos(nombre,activo) values ('Expensas',true),('Prepaga',true),('Monotributo',true),('Seguro Auto',true),('Seguros Adicionales',true),('Luz',true),('Agua',true),('Gas',true),('Internet',true),('Telefonía',true),('Transporte / Auto',true),('Supermercado',true),('Mascota (Chancho)',true),('Gimnasio / CrossFit',true),('Salud / Farmacia',true),('Profesional (Colegiatura)',true),('Impuestos y Costos TC',true)
on conflict (nombre) do nothing;

alter table movimientos enable row level security;
alter table tarjetas enable row level security;
alter table categorias enable row level security;
alter table gastos_fijos enable row level security;
alter table medios_pago enable row level security;

create policy "personal_app_movimientos" on movimientos for all using (true) with check (true);
create policy "personal_app_tarjetas" on tarjetas for all using (true) with check (true);
create policy "personal_app_categorias" on categorias for all using (true) with check (true);
create policy "personal_app_fijos" on gastos_fijos for all using (true) with check (true);
create policy "personal_app_medios" on medios_pago for all using (true) with check (true);
